from __future__ import annotations

DEFAULT_ORCHESTRATOR_URL = "http://localhost:8000"
DEFAULT_CF_WORKER_URL = "https://cloudflare-backblaze-worker.pranav-purdue-account.workers.dev"

DEFAULT_HEARTBEAT_INTERVAL_SECONDS = 60
DEFAULT_HEARTBEAT_TIMEOUT_MULTIPLIER = 2.0

DEFAULT_STALE_WORKER_REAPER_INTERVAL_SECONDS = DEFAULT_HEARTBEAT_INTERVAL_SECONDS
DEFAULT_ORPHANED_JOB_REQUEUE_INTERVAL_SECONDS = DEFAULT_HEARTBEAT_INTERVAL_SECONDS
DEFAULT_SBATCH_SUBMISSION_INTERVAL_SECONDS = 60

DEFAULT_CHECKPOINT_POLL_INTERVAL_SECONDS = 300
DEFAULT_ORCHESTRATOR_TIMEOUT_SECONDS = 30.0
DEFAULT_SALAD_API_TIMEOUT_SECONDS = 10.0

DEFAULT_SIGTERM_CHECKPOINT_WAIT_SECONDS = 60
DEFAULT_SIGTERM_CHECKPOINT_POLL_SECONDS = 2
DEFAULT_SIGTERM_PROCESS_WAIT_SECONDS = 10
DEFAULT_SLURM_SIGTERM_MARGIN_SECONDS = 300
