"""Initial schema

Revision ID: f8da36c3c972
Revises:
Create Date: 2026-02-28 22:36:41.285362

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8da36c3c972"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "assigned",
                "running",
                "completed",
                "failed",
                "cancelled",
                name="jobstatus",
            ),
            nullable=False,
        ),
        sa.Column("input_bundle_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("latest_checkpoint_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_checkpoint_at", sa.DateTime(), nullable=True),
        sa.Column("assigned_worker_id", sa.Uuid(), nullable=True),
        sa.Column("slurm_job_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "worker",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("platform", sa.Enum("hpc", "salad", name="platform"), nullable=False),
        sa.Column("gpu_model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("gpu_count", sa.Integer(), nullable=False),
        sa.Column("vram_gb", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("queued", "active", name="workerstatus"), nullable=False),
        sa.Column("provider_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_heartbeat", sa.DateTime(), nullable=False),
        sa.Column("registered_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("worker")
    op.drop_table("job")
    # ### end Alembic commands ###
