"""initial schema

Revision ID: 51c343ab81c6
Revises: 
Create Date: 2026-02-24 00:49:22.564505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '51c343ab81c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'assigned', 'running', 'completed', 'failed', 'cancelled', name='jobstatus'), nullable=False),
    sa.Column('input_bundle_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latest_checkpoint_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_checkpoint_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_worker_id', sa.Uuid(), nullable=True),
    sa.Column('slurm_job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('hpc', 'salad', name='platform'), nullable=False),
    sa.Column('gpu_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gpu_count', sa.Integer(), nullable=False),
    sa.Column('vram_gb', sa.Integer(), nullable=False),
    sa.Column('slurm_job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker')
    op.drop_table('job')
    # ### end Alembic commands ###
